global_costmap:
    global_frame: /map
    robot_base_frame: /base_link
    static_map: true
    rolling_window: false
    track_unknown_space: true

    plugins:
        - {name: static,                  type: "costmap_2d::StaticLayer"}
        - {name: inflation,               type: "costmap_2d::InflationLayer"}
